<?xml version="1.0" encoding="utf-8"?>
<!-- $Revision$ -->
<!-- EN-Revision: d5a500831e9e6e708b64b337d70edb50f6e6989a Maintainer: lex Status: ready -->
<!-- Reviewed: yes Maintainer: lex -->

<phpdoc:classref xml:id="class.mongoprotocolexception" xmlns:phpdoc="http://php.net/ns/phpdoc" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude">

 <title>Класс MongoProtocolException</title>
 <titleabbrev>MongoProtocolException</titleabbrev>

 <partintro>

<!-- {{{ MongoProtocolException intro -->
  <section xml:id="mongoprotocolexception.intro">
   &reftitle.intro;
   <para>
    При обращении к MongoDB 2.6.0 и более поздним версиям, 
    некоторые операции (например, запись) могут вызвать исключение MongoProtocolException, 
    когда ответ от сервера не имеет смысла - например, во время сбоя сети (мы могли прочитать весь ответ) или повреждения данных.
   </para>
   <para>
    Это исключение также выдаётся при попытке использовать новые протоколы, которые поддерживает сервер, 
    например, используя <classname>MongoWriteBatch</classname> при обращении к серверу MongoDB до версии 2.6.0.
   </para>
  </section>
<!-- }}} -->

  <section xml:id="mongoprotocolexception.synopsis">
   &reftitle.classsynopsis;

<!-- {{{ Synopsis -->
   <classsynopsis>
    <ooclass><classname>MongoProtocolException</classname></ooclass>

<!-- {{{ Class synopsis -->
    <classsynopsisinfo>
     <ooclass>
      <classname>MongoProtocolException</classname>
     </ooclass>
     
     <ooclass>
      <modifier>extends</modifier>
      <classname>MongoException</classname>
     </ooclass>
    </classsynopsisinfo>
<!-- }}} -->
    <classsynopsisinfo role="comment">&InheritedProperties;</classsynopsisinfo>
    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('exception.synopsis')/descendant::db:fieldsynopsis)" />

   </classsynopsis>
<!-- }}} -->

  </section>

  <section xml:id="mongoprotocolexception.examples">
   &reftitle.examples;
   <example xml:id="mongoprotocolexception.example.catch">
    <title>Отлавливаем MongoProtocolException</title>
    <para>
     Выполнение следующего примера с MongoDB до 2.6.0 вызовет исключение MongoProtocolException
    </para>
    <programlisting role="php">
<![CDATA[
<?php
$mc = new MongoClient("localhost");
$c = $mc->selectCollection("test", "test");

try {
    $batch = new MongoInsertBatch($c);
} catch(MongoProtocolException $e) {
    echo $e->getMessage();
}
?>
]]>
    </programlisting>
    &examples.outputs.similar;
    <screen>
<![CDATA[
Текущий основной сервер не имеет API записи
]]>
    </screen>
   </example>
  </section>


 </partintro>

</phpdoc:classref>

<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
indent-tabs-mode:nil
sgml-parent-document:nil
sgml-default-dtd-file:"~/.phpdoc/manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->
